config/routes.rb
Technews::Application.routes.draw do
  resources :news

  resources :signups

end

app/models/news.rb
class News
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :url, type: String
  field :name, type: String
  field :twitter, type: String
  field :email, type: String
end

app/models/signup.rb
class Signup
  include Mongoid::Document
  field :email, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/news_controller.rb
require 'open-uri'
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    @people = Signup.all

    respond_to do |format|
      if @news.save

        @people.each do |e|

          emailAddress = e.email

          #Article information
          encoded1 = URI::encode(@news.description)
          encoded2 = URI::encode(@news.title)
          encoded3 = URI::encode(@news.name)

          description = encoded1.gsub(' ','%%%20')
          title = encoded2.gsub(' ','%%%20')
          name = encoded3.gsub(' ','%%%20')
          twitterName = "http://twitter.com/#{@news.twitter}"

          #Set email content. 
          subject = "More%20local%20tech%20news"
          header = "Submitted%20on%20www.OurTechHub.com"
          share = "Please%20help%20the%20Puerto%20Rican%20tech%20community%20by%20sharing%20this:"
          unsubscribe = "To%20unsubscribe%20email:%20justin@customerdevlabs.com"

          #Social Links
          bitly = Bitly.new('rjgonzo','R_e5e13a8afae46931a3091994f4b844d7')

          #Twitter
          twitter = "https://twitter.com/intent/tweet?text=#{description}&url=#{@news.url}"
          twitter_url = bitly.shorten(twitter)
          twitter_final = twitter_url.shorten

          #Facebook
          facebook = "http://www.facebook.com/sharer.php?s=100&p[url]=#{@news.url}&p[title]=#{title}&p[summary]=#{description}"
          fb_url = bitly.shorten(facebook)
          fb_final = fb_url.shorten

          message = "#{header}%0D%0DTitle:%0D%0D#{title}%0D%0DDescription:%0D%0D#{description}%0D%0D#{@news.url}%0D%0DSent%20by:%20#{name},%20#{twitterName}%0D%0D#{share}%0D%0DFacebook:%20#{fb_final}%20,%20Twitter:%20#{twitter_final}%0D%0D#{unsubscribe}"
          email = "https://sendgrid.com/api/mail.send.json?api_user=rgonzalez&api_key=123456&to=#{emailAddress}&toname=Influencer&subject=#{subject}&text=#{message}&from=#{@news.email}&fromname=#{name}"

          #Send email to request signature (with Sendgrid)  
          ap 'Email Data'
          ap email
          HTTParty.get(email)
      end

        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news, :callback => params[:callback] }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @signups }
    end
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
    @signup = Signup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @signup }
    end
  end

  # GET /signups/new
  # GET /signups/new.json
  def new
    @signup = Signup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @signup }
    end
  end

  # GET /signups/1/edit
  def edit
    @signup = Signup.find(params[:id])
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(params[:signup])

    respond_to do |format|
      if @signup.save
        format.html { redirect_to @signup, notice: 'Signup was successfully created.' }
        format.json { render json: @signup, status: :created, location: @signup, :callback => params[:callback] }
      else
        format.html { render action: "new" }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /signups/1
  # PUT /signups/1.json
  def update
    @signup = Signup.find(params[:id])

    respond_to do |format|
      if @signup.update_attributes(params[:signup])
        format.html { redirect_to @signup, notice: 'Signup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup = Signup.find(params[:id])
    @signup.destroy

    respond_to do |format|
      format.html { redirect_to signups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Technews</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label 'Your Name' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Your Twitter' %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label 'Your Email' %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<h1>Listing news</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><%= news.title %></td>
    <td><%= news.description %></td>
    <td><%= news.url %></td>
    <td><%= link_to 'Show', news %></td>
    <td><%= link_to 'Edit', edit_news_path(news) %></td>
    <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @news.title %>
</p>

<p>
  <b>Description:</b>
  <%= @news.description %>
</p>

<p>
  <b>Url:</b>
  <%= @news.url %>
</p>


<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>

app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <% if @signup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signup.errors.count, "error") %> prohibited this signup from being saved:</h2>

      <ul>
      <% @signup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signups/edit.html.erb
<h1>Editing signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

app/views/signups/index.html.erb
<h1>Listing signups</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @signups.each do |signup| %>
  <tr>
    <td><%= signup.email %></td>
    <td><%= link_to 'Show', signup %></td>
    <td><%= link_to 'Edit', edit_signup_path(signup) %></td>
    <td><%= link_to 'Destroy', signup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Signup', new_signup_path %>

app/views/signups/new.html.erb
<h1>New signup</h1>

<%= render 'form' %>

<%= link_to 'Back', signups_path %>

app/views/signups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @signup.email %>
</p>


<%= link_to 'Edit', edit_signup_path(@signup) %> |
<%= link_to 'Back', signups_path %>